---
title: "Assignment 5"
output: pdf_document
---

```{r, echo = FALSE, include=FALSE}

##### Load libraries ######


library(tidyverse)
library(fpp3)
library(lubridate)
library(magrittr)
library(forecast)
library(dynlm)
library(fable)
library(tseries)

```



```{r, echo = FALSE, include=FALSE}

### Data retrieval ##

ets = read_csv("http://jmaurit.github.io/analytics/labs/data/eua-price.csv") ## Carbon pricing data
colnames(ets) = c("date", "price")                                                  # Change rownames
elspot = read_csv("http://jmaurit.github.io/norwayeconomy/data_series/elspot.csv") ##




ets["month"] = month(ets$date)
ets["year"] = year(ets$date)

ets_mon = ets %>% group_by(month, year) %>% summarise(
  price = mean(price))

ets_mon["day"] = 1

ets_mon = ets_mon %>% arrange(year, month)

ets_mon = ets_mon %>% mutate(date = make_date(year, month, day))




## Convert to monthly data
ets %<>% 
  mutate(month = month(date)) %>% 
  group_by(month) %>% 
  summarise(ets_mon = mean(price),
            year = year(date),
            month = month,
            day  = 1) %>%  
  ungroup() %>% 
  mutate(date = make_date(year, month, day ))
  



# Join carbon pricing data and 
power_df <- elspot %>% inner_join(ets_mon[c("price", "date")], by="date")
power_DK_df <- power_df %>% dplyr:: select(DK1, DK2, date, price)


## Scale to mwh
power_DK_df %<>% mutate(DK1 = DK1/1000,
                        DK2 = DK2/1000)

# Danish power price and carbon pricing
power_DK_df %>% pivot_longer(cols = -date, names_to = "series", values_to = "prices") %>% 
  ggplot() +
  geom_line(aes(x  = date, y = prices, color = series))



####### Stationarity tests ####

dk_power_ts <- power_DK_df %>% mutate(date = yearmonth(date)) %>%  as_tsibble(index = date)

### ACF and PACF plot
forecast::ggtsdisplay(dk_power_ts$DK1, plot_type='partial',
            lag.max = 24, 
            theme = theme_bw(),
            main = "ACF and PACF plot Danish power prices") 

### PACF plot


adf.test(dk_power_ts$DK1)

unitroot_kpss(dk_power_ts$DK1) # Failed unit root test. Needs differencing

dk_power_ts_diff <- dk_power_ts %>% mutate(DK1 = difference(DK1)) %>% filter(!is.na(DK1)) %>% as_tsibble(index = date)

unitroot_kpss(dk_power_ts_diff$DK1) # Passes. No further differencing

## Build optimal ARIMA model



dk_power_ts_diff %>% fill_gaps() %>%  model(arima = ARIMA(DK1 ~pdq(0,0,0)))


fit_dk_power_arima <- dk_power_ts_diff %>% fill_gaps() %>%   
  model(arima_optimal = ARIMA(DK1, 
                              stepwise = FALSE, 
                              approximation = FALSE))


fc_dk_power_arima <- fit_dk_power_arima %>% forecast(h = 10 )


## Daily consumption data
cons = read_csv2("http://jmaurit.github.io/analytics/labs/data/consumption-per-country_2019_daily.csv")
cons["date"] = as.Date(cons$date, format="%d/%m/%Y")
cons_ts = tsibble(cons, index=date)
cons_ts %>% autoplot(NO)


## Decomposition using STL method
cons_comp = cons_ts %>% model(
  STL(NO ~ trend(window=7) + season(window="periodic"))
) %>% components 

cons_comp %>% autoplot()

cons_ts["NO_sa"] = cons_comp$season_adjust
cons_ts = tsibble(cons_ts, index=date)



cons_ts %>%
  gg_tsdisplay(difference(NO, 7), plot_type='partial') 


```


## Assignment 1: Comparison of variance of consumption data in Norway and Denmark

```{r, echo = TRUE}

## Seasonal decompositon of Danish electricity consumption

cons_comp_dk = cons_ts %>% model(
  STL(DK ~ trend(window=7) + season(window="periodic"))
) %>% components 

cons_comp_dk %>%  autoplot()

##Norwegian decomposition
cons_ts %>% autoplot(NO_sa)

```


```{r, echo = TRUE}
forecast::ggtsdisplay(cons$DK, plot_type='partial',
            lag.max = 24, 
            theme = theme_bw(),
            main = "Norwegian ") 


```


